import { Inter , Aref_Ruqaa } from "next/font/google";
import "./globals.css";

const Aref = Aref_Ruqaa({
  subsets: ["arabic"],
  weight: "400",
  variable: "--font-aref",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Aref.variable}>{children}</body>
    </html>
  );
}
